version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            coverage run -m unittest && coverage xml